Added Spherical Shell Python script and associated files
cnerg/OpenMCActivationStudy pull request #9
Opened 2024-04-05 23:29 UTC by anu1217

-Closed previous pull request due to missing cell filter in the Python script + issues with pushing changes to branch

2024-04-06 15:03 UTC, gonuke requested changes
Thanks @anu1217 - this looks good and matches what I expected.  A couple of little pedantic notes about source strength and related axis titles.  Just trying to make sure things are defined consistently.

2024-04-06 15:03 UTC, gonuke commented on SphericalShell/SphericalShell.py
> +settings.source = openmc.Source(space=PointSource, energy=Prob, strength = 10.0, particle = 'neutron')
Is there a reason for `strength = 10`?  It doesn't really matter in this problem, but just curious why not 1 or something larger to represent a realistic system?

2024-04-06 15:03 UTC, gonuke commented on SphericalShell/SS_h5_Reader.py
> +ax.set_ylabel('Flux [neutron-cm/source]')
This isn't strictly true since you have source strength 10

2024-05-14 21:06 UTC, anu1217 commented on SphericalShell/SphericalShell.py
> +settings.source = openmc.Source(space=PointSource, energy=Prob, strength = 10.0, particle = 'neutron')
There's no particular reason for that number. I think it makes to change the source strength to the default 1.0 so that the flux units are still in terms of per-source-particle.

```suggestion
settings.source = openmc.Source(space=PointSource, energy=Prob, strength = 1.0, particle = 'neutron')
```

2024-05-14 21:07 UTC, gonuke approved these changes

2024-05-14 21:07 UTC, merged